# Generated by Django 3.1.7 on 2021-03-23 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='員工編號')),
                ('empname', models.CharField(max_length=4, verbose_name='員工姓名')),
                ('phonenum', models.CharField(max_length=10, verbose_name='電話號碼')),
                ('position', models.CharField(max_length=1, verbose_name='職位')),
                ('passwd', models.CharField(max_length=20, verbose_name='密碼')),
            ],
        ),
        migrations.CreateModel(
            name='Worksche',
            fields=[
                ('serno', models.AutoField(primary_key=True, serialize=False, verbose_name='流水號')),
                ('workdate', models.DateField(verbose_name='出勤日期')),
                ('workhour', models.IntegerField(verbose_name='出勤時')),
                ('workmin', models.IntegerField(verbose_name='出勤分')),
                ('offhour', models.IntegerField(verbose_name='退勤時')),
                ('offmin', models.IntegerField(verbose_name='退勤分')),
                ('job', models.CharField(choices=[('Kitchen', '廚房'), ('Bar', '吧台'), ('Inside', '內場'), ('Outside', '外場'), ('Usher', '帶位')], max_length=10, verbose_name='崗位')),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.employee', verbose_name='員工編號')),
            ],
        ),
    ]
