# Generated by Django 3.1.7 on 2021-03-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20210331_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksche',
            name='workdate',
            field=models.DateField(verbose_name='出勤日期'),
        ),
    ]
