# Generated by Django 3.1.7 on 2021-03-30 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20210331_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksche',
            name='workdate',
            field=models.DateField(default=datetime.date.today, verbose_name='出勤日期'),
        ),
    ]
