# Generated by Django 3.1.7 on 2021-04-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20210331_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksche',
            name='workhour',
            field=models.CharField(max_length=2, verbose_name='出勤時'),
        ),
    ]
