# Generated by Django 3.1.7 on 2021-05-07 02:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0004_auto_20210507_1045'),
        ('schedule', '0009_auto_20210503_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worksche',
            fields=[
                ('serno', models.AutoField(primary_key=True, serialize=False, verbose_name='流水號')),
                ('workdate', models.DateField(default=datetime.date.today, verbose_name='出勤日期')),
                ('workhour', models.CharField(max_length=2, verbose_name='出勤時')),
                ('workmin', models.CharField(max_length=2, verbose_name='出勤分')),
                ('offhour', models.CharField(max_length=2, verbose_name='退勤時')),
                ('offmin', models.CharField(max_length=2, verbose_name='退勤分')),
                ('job', models.CharField(choices=[('Kitchen', '廚房'), ('Bar', '吧台'), ('Inside', '內場'), ('Outside', '外場'), ('Usher', '帶位')], max_length=10, verbose_name='崗位')),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.employee_data', verbose_name='員工編號')),
            ],
        ),
    ]
