# Generated by Django 3.2.4 on 2021-06-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_worksche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksche',
            name='job',
            field=models.CharField(choices=[('Kitchen', '廚房'), ('Bar', '吧台'), ('Inside', '內場'), ('Outside', '外場'), ('Usher', '帶位')], max_length=10, verbose_name='工作崗位'),
        ),
    ]
