# Generated by Django 3.2.4 on 2021-07-04 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20210507_1045'),
        ('schedule', '0011_alter_worksche_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksche',
            name='empid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.employee_data', verbose_name='員工編號'),
        ),
    ]
