# Generated by Django 3.2.4 on 2021-07-04 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_employee_data_empid'),
        ('schedule', '0012_alter_worksche_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksche',
            name='empid',
            field=models.ForeignKey(default='員工不存在', on_delete=django.db.models.deletion.SET_DEFAULT, to='login.employee_data', verbose_name='員工編號'),
        ),
    ]
