# Generated by Django 3.2.4 on 2021-08-01 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_employee_data_empid'),
        ('schedule', '0013_alter_worksche_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksche',
            name='empid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.employee_data', verbose_name='員工編號'),
        ),
        migrations.AlterField(
            model_name='worksche',
            name='workdate',
            field=models.DateField(verbose_name='出勤日期'),
        ),
    ]
