# Generated by Django 3.2.6 on 2021-08-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_auto_20210801_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksche',
            name='offhour',
            field=models.CharField(choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23')], default='18', max_length=2, verbose_name='退勤時'),
        ),
        migrations.AlterField(
            model_name='worksche',
            name='offmin',
            field=models.CharField(choices=[('00', '00'), ('30', '30')], default='00', max_length=2, verbose_name='退勤分'),
        ),
        migrations.AlterField(
            model_name='worksche',
            name='workhour',
            field=models.CharField(choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('06', '06'), ('07', '07'), ('08', '08'), ('09', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23')], default='09', max_length=2, verbose_name='出勤時'),
        ),
        migrations.AlterField(
            model_name='worksche',
            name='workmin',
            field=models.CharField(choices=[('00', '00'), ('30', '30')], default='00', max_length=2, verbose_name='出勤分'),
        ),
    ]
