# Generated by Django 3.2.4 on 2021-07-03 10:48

import apps.reservation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('serno', models.AutoField(primary_key=True, serialize=False, verbose_name='流水號')),
                ('bookname', models.CharField(max_length=2, verbose_name='姓')),
                ('booktel', models.CharField(max_length=10, verbose_name='電話號碼')),
                ('bookadt', models.PositiveIntegerField(default=0, verbose_name='大人數量')),
                ('bookchd', models.PositiveIntegerField(default=0, verbose_name='小孩數量')),
                ('booktime', models.DateTimeField(verbose_name='時間')),
                ('remark', models.TextField(null=True, verbose_name='備註')),
                ('systime', models.DateTimeField(auto_now_add=True, verbose_name='系統時間')),
            ],
        ),
        migrations.CreateModel(
            name='Wt',
            fields=[
                ('serno', models.AutoField(primary_key=True, serialize=False, verbose_name='流水號')),
                ('wid', models.CharField(default=apps.reservation.models.increment_wait_number, max_length=20, verbose_name='侯位編號')),
                ('wtname', models.CharField(max_length=2, verbose_name='姓')),
                ('wtadt', models.PositiveIntegerField(default=0, verbose_name='大人數量')),
                ('wtchd', models.PositiveIntegerField(default=0, verbose_name='小孩數量')),
                ('wtcheck', models.IntegerField(choices=[(0, '等待中'), (1, '已帶位')], verbose_name='處理狀態')),
            ],
        ),
    ]
