# Generated by Django 3.1.7 on 2021-03-30 16:22

import apps.reservation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookadt',
            field=models.PositiveIntegerField(default=0, verbose_name='大人數量'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookchd',
            field=models.PositiveIntegerField(default=0, verbose_name='小孩數量'),
        ),
        migrations.AlterField(
            model_name='wt',
            name='wid',
            field=models.CharField(default=apps.reservation.models.increment_wait_number, max_length=20, verbose_name='侯位編號'),
        ),
        migrations.AlterField(
            model_name='wt',
            name='wtadt',
            field=models.PositiveIntegerField(default=0, verbose_name='大人數量'),
        ),
        migrations.AlterField(
            model_name='wt',
            name='wtchd',
            field=models.PositiveIntegerField(default=0, verbose_name='小孩數量'),
        ),
        migrations.AlterField(
            model_name='wt',
            name='wtcheck',
            field=models.IntegerField(choices=[(0, '等待中'), (1, '已帶位')], verbose_name='處理狀態'),
        ),
    ]
