# Generated by Django 3.2.4 on 2021-07-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='remark',
            field=models.TextField(blank=True, default='abc', verbose_name='備註'),
            preserve_default=False,
        ),
    ]
