# Generated by Django 3.2.6 on 2021-11-02 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_book_remark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wt',
        ),
    ]
