# Generated by Django 3.2.4 on 2021-06-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20210331_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='booktime',
            field=models.DateField(verbose_name='日期'),
        ),
    ]
