# Generated by Django 3.2.4 on 2021-06-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_book_booktime'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookdate',
            field=models.DateField(null=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='book',
            name='booktime',
            field=models.TimeField(null=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='book',
            name='remark',
            field=models.TextField(null=True, verbose_name='備注'),
        ),
    ]
