# Generated by Django 3.2.4 on 2021-06-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20210629_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookdate',
        ),
        migrations.AlterField(
            model_name='book',
            name='booktime',
            field=models.DateTimeField(default=0, verbose_name='時間'),
        ),
    ]
