# Generated by Django 3.2.4 on 2021-06-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20210629_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='booktime',
            field=models.DateTimeField(verbose_name='時間'),
        ),
    ]
