# Generated by Django 3.1.7 on 2021-05-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderTime', models.DateTimeField(verbose_name='用餐時間')),
                ('date_submit', models.DateTimeField(auto_now=True, verbose_name='提交時間')),
                ('feedback_text', models.TextField()),
            ],
        ),
    ]
