# Generated by Django 3.1.7 on 2021-05-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='聯絡姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='聯絡信箱')),
                ('cometime', models.DateField(auto_now_add=True, verbose_name='光顧時間')),
                ('content', models.TextField(max_length=500, verbose_name='意見回饋')),
            ],
        ),
    ]
