# Generated by Django 3.1.7 on 2021-03-26 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordinfo',
            name='f_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='order.food', verbose_name='餐點編號'),
        ),
        migrations.AddField(
            model_name='ordinfo',
            name='foodq',
            field=models.IntegerField(default=0, verbose_name='數量'),
        ),
        migrations.AddField(
            model_name='ordinfo',
            name='o_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='order.ord', verbose_name='訂單編號'),
        ),
        migrations.AddField(
            model_name='ordinfo',
            name='ordice',
            field=models.CharField(max_length=3, null=True, verbose_name='冰塊'),
        ),
        migrations.AddField(
            model_name='ordinfo',
            name='ordsua',
            field=models.CharField(max_length=3, null=True, verbose_name='甜度'),
        ),
        migrations.AddField(
            model_name='ordinfo',
            name='ordtip',
            field=models.TextField(default='', verbose_name='備註'),
        ),
    ]
