# Generated by Django 3.1.7 on 2021-07-31 16:19

import apps.order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_ord_wid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ord',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='總金額'),
        ),
        migrations.AlterField(
            model_name='ord',
            name='wid',
            field=models.CharField(default=apps.order.models.increment_wait_number, max_length=20, verbose_name='訂單編號'),
        ),
    ]
