# Generated by Django 3.2.6 on 2021-08-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210801_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='foodimage/'),
        ),
        migrations.AddField(
            model_name='food',
            name='on_sales',
            field=models.IntegerField(default=1, max_length=1, verbose_name='是否上架'),
        ),
    ]
