# Generated by Django 3.2.6 on 2021-08-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20210807_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='apps/order/foodimage/', verbose_name='餐點圖片'),
        ),
    ]
