# Generated by Django 3.2.6 on 2021-08-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_food_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='image',
        ),
    ]
