# Generated by Django 3.2.6 on 2021-08-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_remove_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='foodimage', verbose_name='餐點圖片'),
        ),
    ]
