# Generated by Django 3.2.6 on 2021-08-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='isIce',
            field=models.CharField(choices=[('Y', '是'), ('N', '否')], default='N', max_length=128, verbose_name='可調整冰塊'),
        ),
        migrations.AddField(
            model_name='food',
            name='isSug',
            field=models.CharField(choices=[('Y', '是'), ('N', '否')], default='N', max_length=128, verbose_name='可調整甜度'),
        ),
    ]
