# Generated by Django 3.2.6 on 2021-08-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20210807_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordinfo',
            name='foodp',
            field=models.IntegerField(default=0, verbose_name='小結'),
        ),
    ]
