# Generated by Django 3.2.6 on 2021-08-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_ordinfo_foodp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='on_sales',
            field=models.IntegerField(default=1, verbose_name='是否上架'),
        ),
    ]
