# Generated by Django 3.2.6 on 2021-08-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_food_on_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='foodimage', verbose_name='餐點圖片'),
        ),
    ]
