# Generated by Django 3.2.6 on 2021-08-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_alter_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='foodnameEng',
            field=models.CharField(default='', max_length=10, verbose_name='餐點名稱英文'),
        ),
    ]
