# Generated by Django 3.2.6 on 2021-08-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_food_foodnameeng'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordinfo',
            name='unique_id',
            field=models.IntegerField(default=0, verbose_name='專屬ID'),
        ),
    ]
