# Generated by Django 3.2.6 on 2021-10-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_ordinfo_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordinfo',
            name='ordice',
            field=models.CharField(blank=True, choices=[('0', '去冰'), ('1', '微冰'), ('2', '正常冰')], max_length=3, null=True, verbose_name='冰塊'),
        ),
        migrations.AlterField(
            model_name='ordinfo',
            name='ordsua',
            field=models.CharField(blank=True, choices=[('0', '無糖'), ('1', '微糖'), ('2', '正常糖')], max_length=3, null=True, verbose_name='甜度'),
        ),
    ]
