# Generated by Django 3.2.6 on 2021-10-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_auto_20211009_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='foodnameEng',
            field=models.CharField(default='', max_length=50, verbose_name='餐點名稱英文'),
        ),
    ]
