# Generated by Django 3.2.6 on 2021-10-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_alter_food_foodnameeng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordinfo',
            name='ordice',
            field=models.CharField(blank=True, choices=[('去冰', '去冰'), ('微冰', '微冰'), ('正常冰', '正常冰')], max_length=3, null=True, verbose_name='冰塊'),
        ),
        migrations.AlterField(
            model_name='ordinfo',
            name='ordsua',
            field=models.CharField(blank=True, choices=[('無糖', '無糖'), ('微糖', '微糖'), ('正常糖', '正常糖')], max_length=3, null=True, verbose_name='甜度'),
        ),
    ]
