# Generated by Django 3.1.7 on 2021-05-07 02:38

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210503_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_data',
            name='job',
            field=models.CharField(choices=[('Kitchen', '廚房'), ('Bar', '吧台'), ('Inside', '內場'), ('Outside', '外場'), ('Usher', '帶位')], default=django.utils.timezone.now, max_length=10, verbose_name='崗位'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_data',
            name='offhour',
            field=models.CharField(default=django.utils.timezone.now, max_length=2, verbose_name='退勤時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_data',
            name='offmin',
            field=models.CharField(default=django.utils.timezone.now, max_length=2, verbose_name='退勤分'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_data',
            name='workdate',
            field=models.DateField(default=datetime.date.today, verbose_name='出勤日期'),
        ),
        migrations.AddField(
            model_name='employee_data',
            name='workhour',
            field=models.CharField(default=django.utils.timezone.now, max_length=2, verbose_name='出勤時'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee_data',
            name='workmin',
            field=models.CharField(default=django.utils.timezone.now, max_length=2, verbose_name='出勤分'),
            preserve_default=False,
        ),
    ]
