# Generated by Django 3.1.7 on 2021-05-07 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210507_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_data',
            name='job',
        ),
        migrations.RemoveField(
            model_name='employee_data',
            name='offhour',
        ),
        migrations.RemoveField(
            model_name='employee_data',
            name='offmin',
        ),
        migrations.RemoveField(
            model_name='employee_data',
            name='workdate',
        ),
        migrations.RemoveField(
            model_name='employee_data',
            name='workhour',
        ),
        migrations.RemoveField(
            model_name='employee_data',
            name='workmin',
        ),
    ]
