# Generated by Django 3.2.4 on 2021-08-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_employee_data_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_data',
            name='empid',
            field=models.CharField(max_length=5, unique=True, verbose_name='員工編號'),
        ),
    ]
