# Generated by Django 3.2.6 on 2021-08-07 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0006_alter_employee_data_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_data',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empdata', to=settings.AUTH_USER_MODEL),
        ),
    ]
