# Generated by Django 3.2.6 on 2021-10-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_employee_data_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_data',
            name='status',
            field=models.CharField(default='在職', max_length=10, verbose_name='員工狀態'),
        ),
    ]
