# Generated by Django 3.2.6 on 2021-10-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_employee_data_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_data',
            name='status',
            field=models.CharField(choices=[('在職', 'Working'), ('離職', 'Quit'), ('暫休', 'Rest'), ('其他', 'Others')], default='在職', max_length=10, verbose_name='員工狀態'),
        ),
    ]
