# Generated by Django 3.2.6 on 2021-10-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_employee_data_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_data',
            name='status',
            field=models.CharField(choices=[('1', '在職'), ('4', '離職'), ('2', '暫休'), ('3', '其他')], default='在職', max_length=10, verbose_name='員工狀態'),
        ),
    ]
